export const GET_SERVER_INFO = 'GET_SERVER_INFO'
export const GET_CLIENTSTASTICSRANGE = 'GET_CLIENTSTASTICSRANGE'
// export const UPDATE_BRUSHEDSELECTION = 'UPDATE_BRUSHEDSELECTION'
export const GET_CLIENT_PARA = 'GET_CLIENT_PARA'
